services:
  database:
    container_name: database
    build:
      context: ./postgres14
      dockerfile: Dockerfile
    # image: "postgres:14"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"

  omeroserver:
    # container_name: omero-server
    # build:
    #   context: ./omero-server
    #   dockerfile: Dockerfile
    image: "openmicroscopy/omero-server:5"
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "omero:/OMERO"
    ulimits:
      nofile:
        soft: 8192
        hard: 65536

  # omeroweb:
  #   container_name: omero-web
  #   build:
  #     context: ./omero-web
  #     dockerfile: Dockerfile

  omerowebstandalone:
    # container_name: omero-web-standalone
    # build:
    #   context: omero-web/standalone
    #   dockerfile: Dockerfile
    # depends_on:
    #   - omeroweb
    image: "openmicroscopy/omero-web-standalone:5"
    environment:
      OMEROHOST: omeroserver
    networks:
      - omero
    ports:
      - "4080:4080"

networks:
  omero:

volumes:
  database:
  omero:
