---
- hosts: vm_omero # all
  roles:
    - role: ome.postgresql
      postgresql_databases:
        - name: omero
      postgresql_users:
        - user: omero
          password: omero
          databases: [omero]
    - role: ome.omero_server
      omero_server_selfsigned_certificates: true
      omero_server_rootpassword: ChangeMe
    - role: ome.omero_web
  vars:
    ansible_python_interpreter: /usr/bin/python3
    omero_server_python3: True
    omero_server_system_uid: 1000
    omero_server_virtualenv: True
    postgresql_version: "14"
  tasks:
    - name: Display IP
      debug:
        msg: "IP address VM: {{ ansible_host }}"
